Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 35

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/update'
